language: python
python: "2.7"
dist: trusty
sudo: required
cache: pip
addons:
  postgresql: "9.4"
  apt:
    packages:
      - dh-virtualenv
      - libc6-i386
      - debhelper
git:
  depth: 2000

services:
  - postgresql
  - redis-server
  - docker
env:
  global:
    - SQLALCHEMY_DATABASE_URI='postgresql://postgres:@localhost/portal_unit_tests'
    - LOG_FOLDER='/tmp/shared_service_log'
    - PERSISTENCE_FILE='https://raw.githubusercontent.com/uwcirg/TrueNTH-USA-site-config/develop/site_persistence_file.json'

matrix:
  include:
    - env: TOXENV=docs
    - env:
        - TOXENV=ui

        # _SAUCE_USERNAME
        - secure: "Hc5NUBDw0sUdXVTn0s8NqcmabMYZiMrpq3x5+Nytze4JKRxk0kmhyt IurC/C3A6bDM622ZFVtTCAs8k4Cg4GBfuGrdC/EaVaolw7trhWY9TUEuwWSPlmdTs ChPDQpGxXngxEA7ij2D6BOUR97l3UrXtMQ24syVHJl8MiLoZelNKSnQCs8yeNMw+j iLTvCyAXTl4hfoUiRidVxUlCTcSgJ4xajBDPEgAIm82Oo4qnCz7PSt/9GSG7cC5qH +KllMGbn/a8kTM+kJxiWA1QLQ7+DNo0TiYX1dMyZQPhPE/8H7EfLLvIuEAAvKNg3Y VxfpZYNDOKadP28HjSUqexbh75KBt8KZGweymLKPK/bt8zwAtWufEqW2iESlOfURz jKZ451oaBmCEpaFbbsxc6lnGQxnKB4/YTx6jClXTjii2dqUUw/lUIYgFXfnRYoyfo HGrl+AzZiVV4knJfQFHNT7rZoKfzgqzLUlkMYQu9sLKzfSb4ZT3MSFUnATfHmczmC 9JnX0aCtSj6V6ab6+PovFyFHRKhmn/zVAxUq0hFVdqZQj7A6nIU+vx8fpa42BRjA9 muaz3MwYIr5dAAlF1wPh3XRWx0mRW6YK4WYQ3HaV1nol9wGAnnTM0l949CN0u3IS6 WorfdmGuccFT0DT39qNyu5tnJ2W2hab7Dg2fJ+oabhEQ="

        # _SAUCE_ACCESS_KEY
        - secure: "jj5q57S8VzAHlNUlSrKtRdoCbFKFig75CFA8AxAQ0lyoMi9VOzwoNQ S3A50I0OYONhqiMWOeyxaBX+eS6y50kYoholJ8yy2DEzaYAJKGGrCh/S6YsGqBo9w jqODynf8c9uDeq4uyNqm3xrOuOBhYUWlmzczILkegw9cvBmKjMM8KK0OxwoEZlQC+ XqZMtUj0oxjiqyK5BiSDBt1TM8pLbZDUup0JTXzuxrRKjZnmw/LtMRqE5P64JeM7d 7qvcYwFrAMydUZSCIO9hguRjmL+kX2cl7Z0lTk5fAtcsroeDy63ClA2v/I90D4Bq2 v90jujU38P7ukJFLR4ji8HRKTllIJ1ouYoR4gzrWLQt7vXL7tHfByaCf4jFOqRaSd dEzj7xn4dXA/CbmbsNQSb+vFMVJMdND3RQDNYXcnGe/jlrn01UdHkouVui0SGtdl2 CHd8GfynkWhlw8XnZ6YZwdM8TVkYrFJPyD2hh7RyOzjytQb6gGdPVbztfEbgAjwXe af9/+Hi/aNdTlvF+KOZYr1Jkf5L2XTUxQhsNt+M2VMLzX03VOivlXZbRKC72b+hGv q93ENiMOt4uhT4d74KuTeXU19QelUWD5tYUiWEsIFvzz/g1+xVShU4DcNLKRIoYZY 1H4w95+QFRBZ9oXHRO7auua4QneIsFBq1ghQ/E7jfVOs="
      addons:
        postgresql: "9.4"
        sauce_connect: true

before_install:
  # Set TOXENV default (if not overridden by matrix environmental variables)
  - if [[ ! -v TOXENV ]]; then export TOXENV=py27;fi

  # Allow environmental variables configured per-repo on TravisCI website to override .travis.yml defaults
  - if [[ ! -v SAUCE_USERNAME ]]; then export SAUCE_USERNAME=$_SAUCE_USERNAME;fi
  - if [[ ! -v SAUCE_ACCESS_KEY ]]; then export SAUCE_ACCESS_KEY=$_SAUCE_ACCESS_KEY;fi


  - psql -c 'create database portal_unit_tests owner postgres;' -U postgres

  - pip install --upgrade pip

install:
  - pip install tox

script:
  - tox

before_deploy:
  # Use make-deb to update changelog so version is correct in package filename
  - pip install make-deb
  - yes | make-deb
  - git checkout debian/rules

  - export PORTAL_VERSION="$(grep portal debian/changelog | awk -F"[()]" '{print $2}')"

  # Build bintray descriptor file dynamically
  - >
    printf '
    {
        "package": {
            "name": "true_nth_usa_portal",
            "repo": "true_nth",
            "subject": "ivan-c",
            "public_download_numbers": false,
            "public_stats": false
        },
        "version": {
            "name": "%s",
            "gpgSign": true
        },
        "files": [
            {
                "includePattern": "../(.+\\.deb)$",
                "uploadPattern": "/$1",
                "matrixParams": {
                    "deb_distribution": "stable",
                    "deb_component": "main",
                    "deb_architecture": "amd64"
                }
            }
        ],
        "publish": true
    }
    ' "$PORTAL_VERSION"
    > "${TRAVIS_BUILD_DIR}/bintray.json"
  - docker build --file docker/build --tag "portal_builddeb:test" .
  - docker cp $(docker ps --latest --quiet):/tmp/artifacts /tmp
  - cp /tmp/artifacts/* ../

# Only deploy from default virtual env TravisCI job
deploy:
  on:
    all_branches: true
    condition: $TOXENV = py27
  provider: bintray
  file: "bintray.json"
  user: "ivan-c"
  key:
    secure: M9cm19G950npuMpgpwe76ZsccMtDjaXvnGwWWjwK4sGqUv1jnE4+6bJ4fZ4PM/yQNVomjZ2Etdv6AHzsSmsV954Sk1GKqGt7BKCDCmCrQpSLduU6vsYDswbyjMXihlWNfLdMOe7pO/k9J9GDStCDnUEjCB6R5yCN+F8o9RAUm+4SvASwn0t9e7isFnGxVirSqbTTVlNw8L+qVwWkGdWHxOBCfCj//r6E3GdqkffvitZ9/uO3suCpJ74pRdeZyXOeERHEutZIGDWNyxvmpI1JjxLvFeGTh+AIaK70d2o6vORVNK/skbc+BCXPskYDi+7Nhl7mspuDn1UvbkR32mTjOuNBfxGfD6ISkb8dEd1hrQPWLfYToh5SvBa8gCZy0IbsTyJKdGhABYiHbl670JE+dHx+IZjA49K706Xilits4l0m3yMc3AP4O2R4ARGWSQUpLcxc1J8b/lZz8UKBKB6y3Iia7W3yxXntfDNDvhA45+rgHDS5XVTe0cYiwojqhjWrMm0pyxCEzRJ6Bv9ybGrrVZi+gwu2/zbes0CC0nkUswPAcSMrRODEmkGhrpxMNHK8OsoxmUk4VoejcQ9IlvqeIGXqiMgn5V6Q6/K7YJ7KbBavo0hTmDPUJRJzUNJn1FyJsSdeiErGWZAiR+mfyRy90LsiT0fdU9aCYGRgegTlcN0=
