sudo: true
language: python
python:
  - "2.7"

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: "9.5"
services:
  - postgresql
  - redis-server

before_install:
  - sudo service postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y autoremove
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
  - sudo apt-get update
  - sudo apt-get -y install postgresql-9.5
  - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo sed -i 's|port = 5433|port = 5432|' /etc/postgresql/9.5/main/postgresql.conf
  - sudo service postgresql restart 9.5
  - sudo -u postgres createuser test_user
  - sudo -u postgres psql -c "ALTER USER test_user WITH PASSWORD '4tests_only'"
  - psql --version

install:
  - pip install --process-dependency-links -e .
  - cp portal/application.cfg.travis portal/application.cfg

before_script:
 - psql -c 'create database portal_unit_tests owner test_user;' -U postgres
 - celery worker --detach -A portal.celery_worker.celery --loglevel=info

script:
  - nosetests -v --with-cover --cover-package=portal
