---
version: '2.1'
services:
  web:
    # Workaround to gunicorn sync workers bug
    # https://github.com/benoitc/gunicorn/issues/1194
    entrypoint: '/bin/bash -c "source /opt/venvs/portal/bin/activate && env && flask sync && gunicorn --timeout 90 --keep-alive 75 --bind 0.0.0.0:8008  manage:app"'
    # Todo: fix tagging of "latest" and "stable" on TravisCI
    image: "uwcirg-portal-docker.jfrog.io/${IMAGE_NAME:-portal_web}:e4bef52c7eb0c9e647397808f59afa3a60a8473f"
    ports:
      - "${EXTERNAL_PORT:-8080}:${PORT:-8008}"
    env_file:
      - portal.env
    environment:
      - PERSISTENCE_FILE=${PERSISTENCE_FILE:-https://raw.githubusercontent.com/uwcirg/TrueNTH-USA-site-config/develop/site_persistence_file.json}
      # compose-specific overrides
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI:-postgresql://postgres:@db/postgres}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379/0}
      - REQUEST_CACHE_URL=${REQUEST_CACHE_URL:-redis://redis:6379/0}
      - SESSION_REDIS_URL=${SESSION_REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - "6379"
  db:
    image: postgres
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local
