---
version: "3.3"
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - debian_repo="${DEBIAN_REPO:-http://dl.bintray.com/v1/content/uwcirg/${BINTRAY_DEB_REPO:-true_nth}}"

  builder:
    build:
      context: ..
      dockerfile: docker/Dockerfile.build
    environment:
      - BRANCH=${BRANCH:-develop}
      - REPO_SLUG=${REPO_SLUG:-uwcirg/true_nth_usa_portal}
    volumes:
      - debian-repo:
    volumes:
      - source: debian-repo
        target: /tmp/artifacts
        type: volume
volumes:
    debian-repo: {}
