---
version: '2'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    links:
      - db
      - redis
  redis:
    image: redis
    ports:
      - "6379"
  db:
    image: postgres
    ports:
      - "5432"
