---
version: '2.1'
services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${EXTERNAL_PORT:-8080}:80"
    environment:
      - APACHE_SERVER_NAME
      - PERSISTENCE_FILE
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - "6379"
  db:
    image: postgres
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local
